'use client';
import { useState } from 'react';
import { useTheme } from 'next-themes';
import { Save,Trash2,Plus } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '@/lib/client';
import { useResource,ErrorBox,Busy,Loading } from '@/components/common';
import { Button } from '@/components/ui/button';
import { FilterEditor } from '@/components/filter-editor';
import type { Settings,List } from '@/types/app';
export default function SettingsPage(){const saved=useResource<Settings>('settings'),blacklist=useResource<{id:string;username:string}[]>('blacklist'),lists=useResource<List[]>('imports'),[custom,setCustom]=useState<Settings|null>(null),[names,setNames]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),{setTheme}=useTheme();const value=custom??saved.data;
  async function save(){setBusy('settings');setError('');try{await api('settings',value);setTheme(value!.theme);toast.success('Sozlamalar saqlandi');saved.reload();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
  async function add(){setBusy('blacklist');try{await api('blacklist',{usernames:names});setNames('');blacklist.reload();toast.success('Qora ro‘yxat yangilandi');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
  async function remove(id:string){setBusy(id);try{await api('blacklist',{id},'DELETE');blacklist.reload();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
  return <><div className="page-heading"><h1>Sozlamalar</h1><p>O‘zingizga mos tanlov tajribasini yarating.</p></div><ErrorBox message={error||saved.error}/>{!value?<Loading/>:<div className="stack"><div className="panel stack"><h2>Asosiy sozlamalar</h2><div className="grid2"><label>Ilova nomi<input value={value.appName} maxLength={40} onChange={e=>setCustom({...value,appName:e.target.value})}/></label><label>Standart g‘oliblar soni<input type="number" min={1} max={100} value={value.winnerCount} onChange={e=>setCustom({...value,winnerCount:Number(e.target.value)})}/></label><label>Animatsiya davomiyligi<select value={value.animationDuration} onChange={e=>setCustom({...value,animationDuration:Number(e.target.value)})}>{[0,3,4,5].map(s=><option value={s} key={s}>{s===0?'Animatsiyasiz':s+' soniya'}</option>)}</select></label><label>Rang rejimi<select value={value.theme} onChange={e=>setCustom({...value,theme:e.target.value as Settings['theme']})}><option value="system">Tizim</option><option value="light">Yorug‘</option><option value="dark">Qorong‘i</option></select></label><label>Til<select value="uz" disabled><option value="uz">O‘zbekcha</option></select><small>Rus va ingliz tillari uchun lug‘at tuzilmasi tayyor.</small></label></div></div><div className="panel stack"><h2>Standart giveaway filtrlari</h2><FilterEditor value={value.filters} onChange={filters=>setCustom({...value,filters})} lists={lists.data??[]}/><div><Button disabled={!!busy} onClick={save}>{busy==='settings'?<Busy/>:<Save size={17}/>}Sozlamalarni saqlash</Button></div></div><div className="panel stack"><h2>Qora ro‘yxat</h2><p className="muted" style={{fontSize:14}}>Har qatorda bitta username kiriting. Katta-kichik harflar va @ belgisi bir xil hisoblanadi.</p><label>Username’lar<textarea value={names} onChange={e=>setNames(e.target.value)} placeholder={'@username\nusername'} maxLength={30000}/></label><div><Button variant="secondary" disabled={!!busy||!names.trim()} onClick={add}>{busy==='blacklist'?<Busy/>:<Plus size={16}/>}Qora ro‘yxatga qo‘shish</Button></div><div className="row">{blacklist.data?.map(b=><span className="tag tag-gray" key={b.id}>@{b.username}<button disabled={!!busy} aria-label={b.username+'ni qora ro‘yxatdan chiqarish'} onClick={()=>remove(b.id)} style={{border:0,background:'transparent',color:'inherit',padding:6}}><Trash2 size={14}/></button></span>)}</div>{!blacklist.data?.length&&<p className="muted" style={{fontSize:14}}>Qora ro‘yxat bo‘sh.</p>}</div></div>}</>;
}
