'use client';
import Link from 'next/link';
import { usePathname,useRouter } from 'next/navigation';
import { useState } from 'react';
import { useTheme } from 'next-themes';
import { LayoutDashboard,Gift,Users,Link2,Settings,LogOut,Menu,ShieldCheck,Sun,Moon,Plus,ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import { Brand } from './brand';
import { Button } from './ui/button';
import { api } from '@/lib/client';
const links=[{href:'/dashboard',label:'Bosh sahifa',icon:LayoutDashboard},{href:'/dashboard/giveaways',label:'Giveaway’lar',icon:Gift},{href:'/dashboard/participants',label:'Ishtirokchilar',icon:Users},{href:'/dashboard/integrations',label:'Integratsiyalar',icon:Link2},{href:'/dashboard/settings',label:'Sozlamalar',icon:Settings}];
export function DashboardShell({children,email}:{children:React.ReactNode;email:string}){const router=useRouter(),path=usePathname(),[open,setOpen]=useState(false),{resolvedTheme,setTheme}=useTheme();const current=links.find(l=>l.href==='/dashboard'?path===l.href:path.startsWith(l.href));return <><aside className={'sidebar'+(open?' open':'')}><Brand/><span className="eyebrow" style={{margin:'0 13px 15px'}}>ISH MAYDONI</span><nav>{links.map(l=><Link key={l.href} href={l.href} className={'nav-link'+(current?.href===l.href?' active':'')} onClick={()=>setOpen(false)}><l.icon size={19}/>{l.label}</Link>)}</nav><Button asChild style={{marginTop:28}}><Link href="/dashboard/new" onClick={()=>setOpen(false)}><Plus size={17}/> Yangi giveaway</Link></Button><div className="sidebar-bottom"><div className="sidebar-note"><ShieldCheck size={21} color="var(--accent)"/><h3 style={{margin:'8px 0 4px',fontSize:14}}>Har bir tanlov shaffof</h3><p className="muted">Natijalar serverda tanlanadi va tekshiruv hashi bilan saqlanadi.</p></div><button className="nav-link" style={{border:0,background:'transparent'}} onClick={async()=>{try{await api('auth',{action:'logout'});router.replace('/login');router.refresh();}catch(e){toast.error((e as Error).message);}}}><LogOut size={18}/> Hisobdan chiqish</button></div></aside>{open&&<button aria-label="Menyuni yopish" onClick={()=>setOpen(false)} style={{position:'fixed',inset:0,zIndex:29,background:'transparent',border:0}}/>}<div className="workspace"><header className="topbar"><div className="row"><Button variant="ghost" className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Menyu"><Menu size={20}/></Button><span className="muted" style={{fontSize:14}}>Ish maydoni</span><ChevronRight size={14} className="muted"/><span style={{fontSize:14}}>{path==='/dashboard/new'?'Yangi giveaway':current?.label??'Giveaway'}</span></div><div className="row"><Button variant="ghost" aria-label="Rang rejimini almashtirish" onClick={()=>setTheme(resolvedTheme==='dark'?'light':'dark')}>{resolvedTheme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</Button><span className="avatar">{email.slice(0,1).toUpperCase()}</span><span className="topbar-email" style={{fontSize:13}}>{email}</span></div></header><main>{children}</main></div></>;}
