'use client';
import type { GiveawayFilters } from '@/types/giveaway';
import type { List } from '@/types/app';
export function FilterEditor({value,onChange,lists=[],manual=false}:{value:GiveawayFilters;onChange:(filters:GiveawayFilters)=>void;lists?:List[];manual?:boolean}){
  const change=<K extends keyof GiveawayFilters>(key:K,v:GiveawayFilters[K])=>onChange({...value,[key]:v});
  const toggles:{key:keyof GiveawayFilters;label:string;commentOnly?:boolean}[]=[{key:'uniqueUsersOnly',label:'Bir odam = bitta imkoniyat'},{key:'excludePreviousWinners',label:'Oldingi g‘oliblarni chiqarib tashlash'},{key:'excludeBlacklisted',label:'Qora ro‘yxatdagilarni chiqarib tashlash'},{key:'includeReplies',label:'Javob kommentlarini ham hisoblash',commentOnly:true},{key:'excludeEmptyComments',label:'Bo‘sh kommentlarni chiqarib tashlash',commentOnly:true},{key:'filterDuplicateMentions',label:'Bir xil odamlarni mention qilgan takroriy kommentlarni filtrlash',commentOnly:true}];
  const followers=lists.filter(l=>l.type==='followers');
  return <div className="stack"><div className="filters-grid">{toggles.filter(t=>!manual||!t.commentOnly).map(t=><label className="check-label" key={t.key}><input type="checkbox" checked={Boolean(value[t.key])} onChange={e=>change(t.key,e.target.checked)}/>{t.label}</label>)}</div>{!manual&&<><div className="grid2"><label>Kommentda quyidagi so‘z bo‘lishi shart<input value={value.requiredKeyword} onChange={e=>change('requiredKeyword',e.target.value)} placeholder="Masalan: BESH BOLA" maxLength={200}/></label><label>Majburiy hashtag<input value={value.requiredHashtag} onChange={e=>change('requiredHashtag',e.target.value)} placeholder="#giveaway" maxLength={100}/></label><label>Kamida nechta @username belgilansin?<select value={value.requiredMentions} onChange={e=>change('requiredMentions',Number(e.target.value))}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n===0?'Talab yo‘q':n+' ta'}</option>)}</select></label><label className="check-label" style={{alignSelf:'center'}}><input type="checkbox" checked={value.keywordCaseSensitive} onChange={e=>change('keywordCaseSensitive',e.target.checked)}/>Katta-kichik harflar farqlansin</label><label>Sanadan (UTC)<input type="date" value={value.dateFrom??''} onChange={e=>change('dateFrom',e.target.value||null)}/></label><label>Sanagacha (UTC)<input type="date" value={value.dateTo??''} onChange={e=>change('dateTo',e.target.value||null)}/></label></div></>}<div className="section-line stack"><label className="check-label"><input type="checkbox" disabled={!followers.length} checked={value.followerCheckMode==='IMPORTED_FOLLOWERS_MATCH'} onChange={e=>onChange({...value,followerCheckMode:e.target.checked?'IMPORTED_FOLLOWERS_MATCH':'NOT_CHECKED',followerListId:e.target.checked?(value.followerListId??followers[0]?.id??null):null})}/>Faqat obunachilar orasidan tanlash</label>{value.followerCheckMode==='IMPORTED_FOLLOWERS_MATCH'&&<label>Obunachilar ro‘yxati<select value={value.followerListId??''} onChange={e=>change('followerListId',e.target.value)}><option value="">Ro‘yxatni tanlang</option>{followers.map(l=><option key={l.id} value={l.id}>{l.name} · {l.valid_rows} ta</option>)}</select></label>}<p className="notice">Instagram rasmiy API’si barcha follower username’larini bermaydi. {followers.length?'Tekshiruv siz import qilgan ro‘yxat bilan bajariladi.':'“Ishtirokchilar” sahifasida obunachilar ro‘yxatini import qiling.'}</p></div></div>;
}
