'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, ShieldCheck } from 'lucide-react';
import { api } from '@/lib/client';
import { Button } from './ui/button';
import { Brand } from './brand';
import { Busy,ErrorBox } from './common';
export function LoginForm({configured,demo}:{configured:boolean;demo:boolean}){
  const router=useRouter(); const [signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setMessage('');const form=new FormData(event.currentTarget);try{const result=await api<{confirmationRequired:boolean}>('auth',{action:signup?'signup':'login',email:form.get('email'),password:form.get('password')});if(result.confirmationRequired)setMessage('Email manzilingizga tasdiqlash havolasi yuborildi.');else {router.replace('/dashboard');router.refresh();}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="auth-screen"><aside className="auth-brand-panel"><Brand/><div className="stack"><span className="tag" style={{width:'fit-content'}}>Har bir imkoniyat muhim.</span><h1>Keyingi g‘olibingiz shu yerdan boshlanadi.</h1><p style={{color:'#c5bdd9',maxWidth:400}}>Giveaway’laringizni boshqaring, adolatli tanlang va eng hayajonli lahzani auditoriyangiz bilan ulashing.</p></div><div className="row" style={{fontSize:14,color:'#c5bdd9'}}><ShieldCheck size={18}/> Xavfsiz. Shaffof. Oddiy.</div></aside><div className="auth-form"><Brand/><div><h1>{signup?'Hisob yarating':'Xush kelibsiz!'}</h1><p className="muted" style={{marginTop:10}}>{signup?'Birinchi giveaway’ingizga bir qadam qoldi.':'Giveaway’laringizni boshqarish uchun kiring.'}</p></div>{!configured&&<div className="notice">Supabase hali sozlanmagan. Loyiha papkasidagi <b>docs/SUPABASE_SETUP.md</b> bo‘yicha .env.local va bazani sozlang.{demo&&<p style={{marginTop:12}}><Link href="/demo" className="text-link">Demo tanlovni sinab ko‘rish →</Link></p>}</div>}<form onSubmit={submit}><label>Email manzili<input type="email" name="email" required autoComplete="email" placeholder="siz@example.com" disabled={!configured}/></label><label>Parol<input type="password" name="password" minLength={8} maxLength={128} required autoComplete={signup?'new-password':'current-password'} placeholder="Kamida 8 belgi" disabled={!configured}/></label><ErrorBox message={error}/>{message&&<p className="success" role="status">{message}</p>}<Button disabled={busy||!configured}>{busy?<Busy/>:<ArrowRight size={17}/>} {signup?'Hisob yaratish':'Hisobga kirish'}</Button></form><p className="muted" style={{fontSize:14}}>{signup?'Hisobingiz bormi?':'Hali hisobingiz yo‘qmi?'} <button className="text-link" style={{background:'none',border:0}} onClick={()=>{setSignup(!signup);setError('');setMessage('');}}>{signup?'Kirish':'Ro‘yxatdan o‘tish'}</button></p><p className="muted" style={{fontSize:12}}>Davom etish orqali <Link href="/terms" className="text-link">foydalanish shartlari</Link> va <Link href="/privacy" className="text-link">maxfiylik siyosati</Link> bilan tanishganingizni bildirasiz.</p></div></div>;
}
