'use client';
import { useRef,useState } from 'react';
import { motion,useReducedMotion } from 'framer-motion';
import { Trophy,Download,Share2,Maximize,Minimize,Smartphone,Monitor,ArrowRight,RotateCw,ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from './ui/button';
import { Busy,ErrorBox } from './common';
import type { Draw } from '@/types/app';
import { APP_NAME } from '@/lib/config';
import { dateLabel } from '@/lib/client';
export function WinnerReveal({title,draw,onDraw,disabled=false,duration=4,demo=false}:{title:string;draw:Draw|null;onDraw:()=>Promise<Draw>;disabled?:boolean;duration?:number;demo?:boolean}){
  const [result,setResult]=useState<Draw|null>(null),[phase,setPhase]=useState<'idle'|'request'|'animation'|'result'>('idle'),[index,setIndex]=useState(0),[record,setRecord]=useState(false),[portrait,setPortrait]=useState(true),[error,setError]=useState(''),[exporting,setExporting]=useState(false),[cycle,setCycle]=useState(0);
  const reduced=useReducedMotion(),card=useRef<HTMLDivElement>(null);const shown=result??draw;const winner=shown?.winners[index]??shown?.winners[0];
  async function start(){setError('');setPhase('request');setIndex(0);try{const saved=await onDraw();setResult(saved);setPhase('animation');const seconds=reduced?0:duration;const interval=window.setInterval(()=>setCycle(c=>c+1),130);await new Promise(resolve=>window.setTimeout(resolve,seconds*1000));window.clearInterval(interval);setPhase('result');if(!reduced){const confetti=(await import('canvas-confetti')).default;confetti({particleCount:100,spread:80,origin:{y:.65},colors:['#9170ef','#ffc77a','#f594cb'],disableForReducedMotion:true,zIndex:100});}}catch(e){setError((e as Error).message);setPhase('idle');}}
  async function download(){if(!card.current)return;setExporting(true);try{const {toPng}=await import('html-to-image');const image=await toPng(card.current,{pixelRatio:2,backgroundColor:'#ffffff',filter:node=>!(node instanceof HTMLElement && node.dataset.export==='hide')});const anchor=document.createElement('a');anchor.href=image;anchor.download=`${APP_NAME}-${winner?.username??'result'}.png`;anchor.click();}catch{toast.error('Rasmni yuklash amalga oshmadi. Qayta urinib ko‘ring.');}finally{setExporting(false);}}
  async function share(){if(!shown||!winner)return;const text=`${title}\nG‘olib: @${winner.username}\n${shown.eligible_count} ishtirokchi orasidan\nSHA-256: ${shown.participant_pool_hash}`;const url=shown.public?window.location.origin+'/verify/'+shown.id:undefined;try{if(navigator.share)await navigator.share({title,text,url});else{await navigator.clipboard.writeText(text+(url?'\n'+url:''));toast.success('Natija nusxalandi');}}catch(e){if((e as Error).name!=='AbortError')toast.error('Natijani ulashib bo‘lmadi.');}}
  const busy=phase==='request'||phase==='animation';
  return <div className={record?'record-mode '+(portrait?'portrait':''):'stack'}>{record&&<Button className="record-close" variant="secondary" onClick={()=>setRecord(false)}><Minimize size={17}/>Yopish</Button>}<div className="between" style={{width:'100%'}}><h2>G‘olibni aniqlash</h2><div className="row"><Button variant="ghost" onClick={()=>setPortrait(!portrait)}>{portrait?<Smartphone size={17}/>:<Monitor size={17}/>} {portrait?'9:16':'16:9'}</Button><Button variant="secondary" onClick={()=>setRecord(!record)}><Maximize size={16}/>Video uchun rejim</Button></div></div><div className="winner-stage" ref={card}><span className="eyebrow">{APP_NAME} {demo?'· DEMO MA’LUMOT':''}</span><h3>{title}</h3><motion.div className="winner-medal" animate={phase==='animation'&&!reduced?{rotate:[-10,10,-10],scale:[1,1.06,1]}:{}} transition={{duration:.6,repeat:phase==='animation'?Infinity:0}}><Trophy size={38}/></motion.div>{phase==='request'?<><Busy/><h2>Natija serverda saqlanmoqda...</h2></>:phase==='animation'?<><div className="winner-handle" aria-live="off">{['Omad kimga kuladi?','Katta lahza yaqin...','Tayyor bo‘ling!'][cycle%3]}</div><p className="muted">G‘olib tanlandi. E’lon qilinmoqda...</p></>:winner&&shown?<><span className="tag tag-green">{winner.is_reserve?'ZAXIRA G‘OLIB':'G‘OLIB'} · #{winner.position}</span><motion.div key={winner.id} initial={reduced?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} className="winner-handle">@{winner.username}</motion.div>{winner.comment_text&&<p style={{maxWidth:480,overflowWrap:'anywhere'}}>{winner.comment_text.slice(0,250)}</p>}<p className="muted">{shown.eligible_count.toLocaleString()} ishtirokchi orasidan<br/><small>{dateLabel(shown.created_at)}</small></p><div className="row muted" style={{fontSize:12}}><ShieldCheck size={14}/>Crypto Secure Random · #{shown.sequence_number}</div></>:<><h2>Keyingi g‘olib kim bo‘ladi?</h2><p className="muted" style={{maxWidth:350}}>Shartlarni tekshiring va tanlovni boshlang. Natija avtomatik saqlanadi.</p></>}<div className="row" data-export="hide">{!busy&&winner&&shown&&index<shown.winners.length-1&&<Button onClick={()=>setIndex(i=>i+1)}>Keyingi g‘olib <ArrowRight size={16}/></Button>}<Button disabled={disabled||busy} onClick={start}>{busy?<Busy/>:winner?<RotateCw size={17}/>:<Trophy size={18}/>} {winner?'Qayta tanlash':'G‘OLIBNI ANIQLASH'}</Button></div></div><ErrorBox message={error}/>{shown&&phase!=='animation'&&phase!=='request'&&<div className="stack" style={{width:'100%'}}><div className="row"><Button variant="secondary" onClick={download} disabled={exporting}>{exporting?<Busy/>:<Download size={16}/>}Natijani PNG saqlash</Button><Button variant="secondary" onClick={share}><Share2 size={16}/>Natijani ulashish</Button>{shown.public&&<a href={'/verify/'+shown.id} target="_blank" rel="noreferrer" className="text-link" style={{fontSize:14}}>Ommaviy tekshiruv ↗</a>}</div><p className="hash">SHA-256: {shown.participant_pool_hash}</p></div>}</div>;
}
