'use client';
import Image from 'next/image';
import { useState } from 'react';
import { Instagram,Link2,Unplug,RefreshCw,ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { api,dateLabel } from '@/lib/client';
import { useResource,ErrorBox,Busy,Loading } from '@/components/common';
import { Button } from '@/components/ui/button';
type Integration={active:boolean;id:string;account:{username:string;account_type?:string;followers_count?:number;profile_picture_url?:string};connected_at:string;token_expires_at:string};
export default function Integrations(){const resource=useResource<{integrations:Integration[];metaConfigured:boolean;externalEnabled:boolean}>('instagram/integrations'),[busy,setBusy]=useState(''),[error,setError]=useState('');
  async function connect(){setBusy('connect');setError('');try{const result=await api<{url:string}>('instagram/oauth/start',{});window.location.assign(result.url);}catch(e){setError((e as Error).message);setBusy('');}}
  async function disconnect(){if(!window.confirm('Instagram hisobi uzilsinmi? Oldingi natijalar saqlanadi.'))return;setBusy('disconnect');try{await api('instagram/integrations',{},'DELETE');resource.reload();toast.success('Instagram hisobi uzildi');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
  async function refresh(){setBusy('refresh');try{await api('instagram/refresh',{});resource.reload();toast.success('Token yangilandi');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
  return <><div className="page-heading"><h1>Integratsiyalar</h1><p>Instagram hisobingiz va ma’lumot manbalarini boshqaring.</p></div><div className="stack"><ErrorBox message={error||resource.error}/>{resource.loading?<Loading/>:<div className="panel stack"><div className="between"><div className="row"><span className="source-icon instagram"><Instagram size={24}/></span><div><h2>Instagram</h2><p className="muted" style={{fontSize:14}}>Meta rasmiy API · Business / Creator</p></div></div><span className="tag tag-green">Rasmiy integratsiya</span></div>{resource.data?.integrations.map(i=><div className="notice stack" key={i.id}><div className="row">{i.account.profile_picture_url&&<Image unoptimized width={36} height={36} src={i.account.profile_picture_url} alt="Instagram avatar" className="avatar" referrerPolicy="no-referrer"/>}<div><h2>@{i.account.username}</h2><small>{i.account.account_type??'Professional'} · {i.account.followers_count??'—'} obunachi</small></div></div><div className="row"><span className={'tag '+(i.active?'tag-green':'tag-gray')}>{i.active?'Ulangan':'Sessiya eskirgan'}</span><small>Ulangan: {dateLabel(i.connected_at)}</small><small>Muddati: {dateLabel(i.token_expires_at)}</small></div><div className="row"><Button variant="secondary" disabled={!!busy} onClick={refresh}>{busy==='refresh'?<Busy/>:<RefreshCw size={16}/>}Tokenni yangilash</Button><Button variant="danger" disabled={!!busy} onClick={disconnect}>{busy==='disconnect'?<Busy/>:<Unplug size={16}/>}Uzish</Button></div></div>)}<p className="muted">Hisobingiz boshqaradigan post va Reel kommentlarini to‘g‘ridan-to‘g‘ri yuklang. Instagram parolingiz ilovada so‘ralmaydi.</p><div><Button onClick={connect} disabled={!!busy||!resource.data?.metaConfigured}>{busy==='connect'?<Busy/>:<Link2 size={17}/>} {resource.data?.integrations.length?'Qayta ulash':'Instagram hisobini ulash'}</Button></div>{!resource.data?.metaConfigured&&<p className="notice">Meta ilovasi hali sozlanmagan. Administrator docs/INSTAGRAM_SETUP.md bo‘yicha ilova ID, secret va OAuth callback manzilini kiritishi kerak.</p>}<div className="section-line row muted" style={{fontSize:14}}><ShieldCheck size={17}/>Access tokenlar serverda AES-256-GCM yordamida shifrlanadi.</div></div>}<div className="grid2"><div className="panel stack"><h3>Tashqi provider</h3><span className="tag" style={{width:'fit-content'}}>{resource.data?.externalEnabled?'Sozlangan':'O‘chirilgan'}</span><p className="muted" style={{fontSize:14}}>Mos API URL va kaliti serverda sozlangandagina faollashadi. Ulanish shartlari docs/EXTERNAL_PROVIDER.md da.</p></div></div><p className="notice">Instagram rasmiy API’si to‘liq follower username ro‘yxatini bermaydi. Obunachilik shartini tekshirish uchun obunachilar ro‘yxatini import qiling.</p></div></>;
}
